CREATE DATABASE PAGINACAO
GO 
USE PAGINACAO 

GO 

CREATE TABLE USUARIO(
ID_USUARIO INT IDENTITY,
NOME_USUARIO VARCHAR(255),
EMAIL_USUARIO VARCHAR(255)
)

GO 

DECLARE @CNT INT = 1 ;

WHILE @CNT < =100
BEGIN 
INSERT INTO USUARIO VALUES (CONCAT('USUARIO - ', @CNT), CONCAT('EMAIL_',@CNT,'@EMAIL.COM'))
SET @CNT = @CNT + 1
END 

GO 

SELECT * FROM USUARIO