USE PAGINACAO 
GO 

IF OBJECT_ID('LISTAR_USUARIO','P') IS NOT NULL
DROP PROCEDURE LISTAR_USUARIO

GO 


CREATE PROCEDURE LISTAR_USUARIO
(
@NOME_USUARIO VARCHAR(255) = NULL,
@ASC          BIT = NULL,
@PAGENUM      INT,
@PAGESIZE     INT
)
AS 
BEGIN 
SET NOCOUNT ON

DECLARE @USUARIOS_POSSIVEIS TABLE ( ID_USUARIO INT , LINHA INT, PRIMARY KEY (ID_USUARIO))

DECLARE @INICIO INT 

SET @INICIO = ( @PAGENUM * @PAGESIZE ) +1  ;

WITH ENCONTRADOS AS 
(
SELECT ID_USUARIO , ROW_NUMBER() OVER(
ORDER  BY
CASE WHEN @ASC = 1 THEN ID_USUARIO END ASC,
CASE WHEN @ASC = 0 THEN ID_USUARIO END DESC ) AS LINHA

 FROM USUARIO
 WHERE ( @NOME_USUARIO IS NULL OR ( @NOME_USUARIO IS NOT NULL AND NOME_USUARIO LIKE '%' + @NOME_USUARIO + '%'))
 
 )

 INSERT INTO @USUARIOS_POSSIVEIS
 SELECT * FROM ENCONTRADOS


 SELECT
   US.ID_USUARIO, 
   US.NOME_USUARIO,
   EMAIL_USUARIO

 FROM USUARIO US
 JOIN @USUARIOS_POSSIVEIS PU	
 ON US.ID_USUARIO = PU.ID_USUARIO
 WHERE LINHA BETWEEN @INICIO AND ( @INICIO + @PAGESIZE) -1


END